### Run as: python leaderboard_4_final_script.py
import sys

class_name = ""
filein = open(class_name + "_2_final.txt", "r")
fileout = open(class_name + "_end_leaderboard_html.html", "w")
data = filein.readlines()

file_tho = "<!DOCTYPE html>\n"
file_tho += "<html>\n"
file_tho += "<head>\n"
file_tho += "<style>\n"
file_tho += "table{\n"
file_tho += "    width:100%;\n"
file_tho += "    border-collapse: collapse;\n"
file_tho += "    margin: 25px 0;\n"
file_tho += "    font-size: 0.9em;\n"
file_tho += "    font-family: Bebas,sans-serif;\n"
file_tho += "    box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);\n"
file_tho += "}\n"
file_tho += "th{\n"
file_tho += "    border-top: 2px solid black;\n"
file_tho += "    border-bottom: 2px solid black;\n"
file_tho += "    background-color: #45f1fb;\n"
file_tho += "    text-align: center;\n"
file_tho += "    font-weight: 900;\n"
file_tho += "    font-size: 1.0em;\n"
file_tho += "    font-family: Bebas,sans-serif;\n"
file_tho += "}\n"
file_tho += "td{\n"
file_tho += "    padding: 0 2.5%;\n"
file_tho += "}\n"
file_tho += "tr{\n"
file_tho += "    border-left: 2px solid #000000;\n"
file_tho += "    border-right: 2px solid #000000;\n"
file_tho += "}\n"
file_tho += "img{\n"
file_tho += "   width:100%;\n"
file_tho += "}\n"
file_tho += "tr:nth-of-type(odd) {\n"
file_tho += "  background-color:#b8fafd;\n"
file_tho += "}\n"
file_tho += "tr:last-child{\n"
file_tho += "  border-bottom: 2px solid #000000;\n"
file_tho += "}\n"
file_tho += "tr:hover{\n"
file_tho += "  background-color:#D4D0E6;\n"
file_tho += "}\n"
file_tho += "td:nth-child(1) {  \n"
file_tho += "  font-weight: 1000;\n"
file_tho += "  font-size: 1.5em;\n"
file_tho += "}\n"
file_tho += "td:nth-child(2) {  \n"
file_tho += "  width:10%;\n"
file_tho += "}\n"
file_tho += "td:nth-child(3) {  \n"
file_tho += "  text-align: center;\n"
file_tho += "  word-spacing: 10px;\n"
file_tho += "}\n"
file_tho += "td:nth-child(4) {  \n"
file_tho += "  font-weight: 1000;\n"
file_tho += "  font-size: 2.5em;\n"
file_tho += "  text-align: center;\n"
file_tho += "  color:#5844bd;\n"
file_tho += "}\n"
file_tho += "td:nth-child(5) {  \n"
file_tho += "  padding:0 5%;\n"
file_tho += "  text-align: center;\n"
file_tho += "}\n"
file_tho += "h2{\n"
file_tho += "  font-weight: 1000;\n"
file_tho += "  font-size: 2em;\n"
file_tho += "  width:100%;\n"
file_tho += "  text-align: center;\n"
file_tho += "  font-family: Bebas,sans-serif;\n"
file_tho += "}\n"
file_tho += "</style>\n"
file_tho += "</head>\n"
file_tho += "<body>\n"
file_tho += "<h2>2022 &nbsp;NCAA &nbsp;JUNIOR &nbsp;LEADERBOARD</h2>\n"
file_tho += "<table>\n"
file_tho += "  <tr>\n"
file_tho += "    <th> </th>\n"
file_tho += "    <th>TEAM</th>\n"
file_tho += "    <th>PLAYER</th>\n"
file_tho += "    <th>OVERALL</th>\n"
file_tho += "    <th>POSITION</th>\n"
file_tho += "  </tr>\n"




for line in data[0:]:
    row = line.split("\t")
    file_tho += "<!-- "+ row[0] +"xxxxxxxxx-->\n"
    file_tho += "  <tr>\n"
    file_tho += "    <td>"+row[0]+"</td>\n"
    file_tho += '    <td><img alt="'+row[2]+'" title="'+row[2]+'" src="'+row[6].rstrip()+'"></td>\n'
    file_tho += '    <td><a href="'+row[5]+'">'+row[1]+'</a></td>\n'
    file_tho += "    <td>"+row[4]+"</td>\n"
    file_tho += "    <td>"+row[3]+"</td>\n"
    file_tho += "  </tr>\n"

file_tho += "</table>\n"
file_tho += "</body>\n"
file_tho += "</html>"

fileout.writelines(file_tho)
fileout.close()
filein.close()
